feat: inline files input type support in functions runtime
teamkeel/keel pull request #1511
Opened 2024-07-05 13:08 UTC by RutZap

`InlineFile` inputs are given to the runtime as a string. The open api schema treats any `InlineFile` as a `string`. When we receive a API request to a action with an `InlineFile` input (given as a dataurl) we do this:

* in the case of an auto action: we store the file, get a `FileData` object back and store that in the database.
* in the case of custom functions, after validation, we decorate the input from a simple string to :

```
{
   "field": {
      "__typename": "InlineFile",
      "dataURL": "data:......."
   }
}
```

this is then passed as request params to the custom function lambda. The JS sdk will parse inputs and when it sees `"__typename": "InlineFile"` it will replace the object with a instance of the `sdk.InlineFile` class.

This then means that we can send a normal json http request like:

```
{
  "image": "data:....."
}
```
and in our custom function we can use the `image` input field as an instance of `sdk.InlineFile`:

```
export default CustomFunction(async (ctx, inputs) => {
  console.log(inputs.image.contentType);
  console.log(inputs.image.size)
  console.log(inputs.image.read()); // this returns a Blob at the moment
});
```

2024-07-05 14:32 UTC, davenewza approved these changes

2024-07-05 14:34 UTC, davenewza reviewed
Mistakenly approved this.  Changing to "comment"

2024-07-05 14:35 UTC, davenewza requested changes
Mistakenly approved this. Changing to "request changes"

2024-07-18 11:18 UTC, davenewza approved these changes
Looks great!!  

What's missing is tests for event subscriptions, assuming that will work out of the box.  If not, let's create a ticket (and do it soon in my opinion)

I think the PR title is wrong though as this is inline files function inputs?

2024-07-18 11:18 UTC, davenewza commented on integration/testdata/jobs_basic/tests.test.ts
> +    image: InlineFile.fromDataURL(dataUrl),
nice

2024-07-18 11:18 UTC, davenewza commented on packages/functions-runtime/src/InlineFile.js
> +    this.url = url;
Also, would it be `url` or would it actually be an S3 path?

2024-07-18 11:18 UTC, davenewza commented on packages/functions-runtime/src/InlineFile.js
> +    this.url = url;
I suppose we can figure this out when doing ModelAPI side of things

2024-07-18 11:18 UTC, davenewza commented on packages/functions-runtime/src/ModelAPI.test.js
> +  expect(row.avatar.size).toEqual(2024);
Is it worth testing the value of `row.file.read()`?

2024-07-18 11:18 UTC, davenewza commented on packages/functions-runtime/src/parsing.js
> +function parseParams(inputs) {
This is great!  👏👏

2024-07-18 11:18 UTC, davenewza commented on runtime/actions/parsing.go
> +func TransformCustomFunctionsInputTypes(schema *proto.Schema, action *proto.Action, input any) (any, error) {
This isn't recursive, which means it will only work for fields at the root level, right?  It's possible that there could be a nested input data structure using Messages

2024-07-18 13:08 UTC, RutZap commented on packages/functions-runtime/src/InlineFile.js
> +    this.url = url;
I'm seeing this as being a S3 path that would be used in `read()` if the dataUrl is not set

2024-07-18 13:10 UTC, RutZap commented on packages/functions-runtime/src/ModelAPI.test.js
> +  expect(row.avatar.size).toEqual(2024);
So in the modelAPi.. the `InlineFile` field is not really an `InlineFile` instance yet. When reading via kysely we're getting the object that's been stored in the db. We need to add a hook of some sort to turn it into a InlineFile instance, but this would be part of the following piece of work which involves modelAPI support for _rich_ input types

2024-07-19 04:38 UTC, davenewza commented on packages/functions-runtime/src/ModelAPI.test.js
> +  expect(row.avatar.size).toEqual(2024);
Ah yes, good point!

2024-07-23 09:10 UTC, RutZap commented on runtime/actions/parsing.go
> +func TransformCustomFunctionsInputTypes(schema *proto.Schema, action *proto.Action, input any) (any, error) {
Agreed. We'll tackle this in a separate PR.

2024-07-23 09:12 UTC, merged